---
- hosts: front
  tasks:
   - name: install deps 1/1
     apt:
      name: nginx-extras
      state: present
- hosts: php
  tasks:
   - name: install deps 1/2
     apt:
      name: php-fpm
      state: present
   - name: install deps 2/2
     apt:
      name: php-cli
      state: present
- hosts: shard
  tasks:
   - name: install deps 1/1
     apt:
      name: nginx-extras
      state: present

